"""PowerPoint tool — generate .pptx presentations."""
import os, uuid

NAME        = "ppt_tool"
DESCRIPTION = "Generate a PowerPoint (.pptx) presentation. Provide slide content as 'Slide Title\\nBullet 1\\nBullet 2\\n---\\nNext Slide\\nBullet...' format."
CATEGORY    = "builtin"
ICON        = "📊"
INPUTS = [
    {"name": "content",  "label": "Slide Content", "type": "textarea",
     "placeholder": "Slide 1 Title\nBullet point 1\nBullet point 2\n---\nSlide 2 Title\nBullet point 1",
     "required": True},
    {"name": "title",    "label": "Presentation Title", "type": "text",
     "placeholder": "My Presentation"},
    {"name": "filename", "label": "Output Filename", "type": "text",
     "placeholder": "presentation.pptx"},
    {"name": "theme",    "label": "Theme Color (hex)", "type": "text",
     "placeholder": "#1a73e8"},
]

DOCS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "generated_docs")


def run(content: str, title: str = "Presentation", filename: str = "",
        theme: str = "#1a73e8") -> dict:
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt, Emu
        from pptx.dml.color import RGBColor
        from pptx.enum.text import PP_ALIGN
        import re

        os.makedirs(DOCS_DIR, exist_ok=True)
        if not filename:
            filename = f"pres_{uuid.uuid4().hex[:8]}.pptx"
        if not filename.endswith(".pptx"):
            filename += ".pptx"
        path = os.path.join(DOCS_DIR, filename)

        # Parse theme color
        hex_color = theme.lstrip("#")
        try:
            accent = RGBColor(int(hex_color[0:2],16), int(hex_color[2:4],16), int(hex_color[4:6],16))
        except Exception:
            accent = RGBColor(0x1a, 0x73, 0xe8)

        prs = Presentation()
        prs.slide_width  = Inches(13.33)
        prs.slide_height = Inches(7.5)

        blank_layout  = prs.slide_layouts[6]   # completely blank
        title_layout  = prs.slide_layouts[0]   # title slide

        def _add_title_slide(prs, main_title):
            slide = prs.slides.add_slide(title_layout)
            slide.shapes.title.text = main_title
            slide.shapes.title.text_frame.paragraphs[0].font.size = Pt(40)
            slide.shapes.title.text_frame.paragraphs[0].font.bold = True
            slide.shapes.title.text_frame.paragraphs[0].font.color.rgb = accent
            # Subtitle
            if len(slide.placeholders) > 1:
                slide.placeholders[1].text = "Generated by Assist Neo"

        def _add_content_slide(prs, slide_title, bullets):
            slide = prs.slides.add_slide(blank_layout)
            W, H = prs.slide_width, prs.slide_height

            # Title bar background
            bg = slide.shapes.add_shape(1, 0, 0, W, Inches(1.2))
            bg.fill.solid()
            bg.fill.fore_color.rgb = accent
            bg.line.fill.background()

            # Title text
            txBox = slide.shapes.add_textbox(Inches(0.4), Inches(0.2), W - Inches(0.8), Inches(0.9))
            tf = txBox.text_frame
            tf.word_wrap = False
            p = tf.paragraphs[0]
            p.text = slide_title
            p.font.size = Pt(28)
            p.font.bold = True
            p.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)

            # Bullets
            if bullets:
                cBox = slide.shapes.add_textbox(Inches(0.6), Inches(1.5), W - Inches(1.2), H - Inches(2.0))
                ctf = cBox.text_frame
                ctf.word_wrap = True
                for i, bullet in enumerate(bullets):
                    if not bullet.strip():
                        continue
                    p = ctf.add_paragraph() if i > 0 else ctf.paragraphs[0]
                    p.text = f"• {bullet.strip()}"
                    p.font.size = Pt(20)
                    p.space_after = Pt(8)

        # Build title slide
        _add_title_slide(prs, title)

        # Parse slides separated by ---
        raw_slides = re.split(r"\n---+\n", content.strip())
        for raw in raw_slides:
            lines = [l for l in raw.strip().splitlines() if l.strip()]
            if not lines:
                continue
            slide_title = lines[0]
            bullets     = lines[1:]
            _add_content_slide(prs, slide_title, bullets)

        prs.save(path)
        return {"message": f"✅ PowerPoint generated! ({len(raw_slides)} slides)\n[📥 Download {filename}](/docs/{filename})",
                "file": f"/docs/{filename}"}

    except ImportError:
        return {"error": "python-pptx not installed. Run: pip install python-pptx"}
    except Exception as e:
        return {"error": f"PPT generation failed: {e}"}
